name: Testing

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install pre-commit
      - name: Lint
        run: pre-commit run --show-diff-on-failure --all-files

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1.9.0
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=<the corresponding version> kim-api=2.3.0`
          environment-name: test-env
          cache-environment: true
          create-args: >-
            -f tests/environment.yml

      - name: Install units
        shell: bash -el {0}
        run: |
          sudo apt-get update
          sudo apt-get -y install units

      - name: Install AFLOW
        shell: bash -el {0}
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg && ./bootstrap-vcpkg.sh && cd ..
          export VCPKG_ROOT=$PWD/vcpkg
          wget https://github.com/aflow-org/aflow/releases/download/v4.0.4/aflow_4.0.4.orig.tar.gz
          tar xf aflow_4.0.4.orig.tar.gz
          cd aflow-4.0.4/src
          cmake --preset release_vcpkg
          cmake --build --preset release_vcpkg -j 4

      - name: Install KIM model
        shell: bash -el {0}
        run: |
          kim-api-collections-management install system LJ_ElliottAkerson_2015_Universal__MO_959249795837_003

      - name: Install
        shell: bash -el {0}
        run: |
          python -m pip install .

      - name: Run tests
        shell: bash -el {0}
        run: |
          export PATH=$PATH:$PWD/aflow-4.0.4/build/release_vcpkg
          cd tests
          pytest

      - name: Run example
        shell: bash -el {0}
        run: |
          git submodule init
          git submodule update
          export PATH=$PATH:$PWD/aflow-4.0.4/build/release_vcpkg
          kim-api-collections-management install user SW_ZhouWardMartin_2013_CdTeZnSeHgS__MO_503261197030_003
          cd examples/CrystalGenomeASEExample__TD_000000654321_000
          python run.py
